### ISSUE TITLE
Can't read the content of the notes anymore

### ISSUE THREAD

**Issue by bepolymathe** [bekoeppel/droidplane#9]
@bekoeppel @silberzwiebel 

This project is great even if I know that it is already old. Its only flaw is that you can't read the content of the notes anymore (not the text of the nodes but the text of the notes). If you could make this change it would allow us to use this software for many years to come!

**Comment by bekoeppel** [comment]
Hi @bepolymathe, could you please share a minimal example Mindmap file to reproduce the problem? (please don't include any sensitive information in the file)

**Comment by bepolymathe** [comment]
Oh wait... i understand that’s only the note in Markdown format or note where a part is markdown (like title). 

[test.zip](https://github.com/bekoeppel/droidplane/files/10508765/test.zip)

**Comment by bekoeppel** [comment]
Thanks, I can reproduce the issue. I can't promise you by when I'll have a fix, as I only work on Droidplane in my freetime. Feel free to submit a pull request.

As a workaround, I suggest you create HTML notes instead of Markdown notes; they should render correctly in Droidplane.

**Comment by bepolymathe** [comment]
> I can't promise you by when I'll have a fix, as I only work on Droidplane in my freetime. Feel free to submit a pull request.

Thanks for that. It would be very useful for me. 



> As a workaround, I suggest you create HTML notes instead of Markdown notes; they should render correctly in Droidplane.

All my workflow is in markdown for sharing reason (rmarkdown for research) and i prefer wait for markdown view. View as plaintext would be great too 🤔

**Comment by bekoeppel** [comment]
Please try this one: https://github.com/bekoeppel/droidplane/blob/master/release/droidplane-v1.0.14/DroidPlane-v1.0.14.apk

**Comment by bepolymathe** [comment]
I have a problem with the .apk 🤔 (error)

**Comment by bepolymathe** [comment]
@bekoeppel (thanks !)

After the update, droidplane crashes...

**Comment by bekoeppel** [comment]
Sorry about that. This one: https://github.com/bekoeppel/droidplane/blob/master/release/droidplane-v1.0.15/DroidPlane-v1.0.15.apk

**Comment by bepolymathe** [comment]
No worries. I just tried the new version with the same test file and I see the markdown code. It's cool.  Thanks a lot!

**Comment by bekoeppel** [comment]
OK thanks for confirming.
